### ISSUE TITLE
JavaFX 12, Netbeans -> Debugging

### ISSUE THREAD

**Issue by swinkel-git** [openjfx/openjfx-docs#100]
Hello, 

I have installed: JavaFX 12, NetBeans 11, Java 12.

I have created a Project (Java with Maven -> Project from Archetype project) exactly as described in the documentation.
I also changed in Netbeans-Project (Properties  -> Actions -> Run project) the Execute goals to "clean javafx:run".
Everything works fine exept debugging. Does anyone have a hint, which Execute goals I have to enter  at "Debug projekt"?

Thank you and have a nice day
Sabrina

**Comment by jperedadnr** [comment]
This is a possible solution for debugging from NetBeans, adding some vm arguments to the run goal. In order to keep the usual run as always, we can add a second execution to the plugin.

Modify your plugin like this:
```
<plugin>
	                <groupId>org.openjfx</groupId>
	                <artifactId>javafx-maven-plugin</artifactId>
	                <version>0.0.2</version>
	                <executions>
	                    <execution>
	                        <id>default-cli</id>
	                        <configuration>
	                            <mainClass>org.openjfx.hellofxml/org.openjfx.hellofxml.App</mainClass>
	                        </configuration>
	                    </execution>
	                    <execution>
	                        <id>debug</id>
	                        <configuration>
	                            <options>
	                                <option>-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:8000</option>
	                            </options>
	                            <mainClass>org.openjfx.hellofxml/org.openjfxml.hellofx.App</mainClass>
	                        </configuration>
	                    </execution>
	                </executions>
	            </plugin>
```

Now you can run from command line: `mvn clean javafx:run`, to run as usual your application, and `mvn clean javafx:run@debug`, to start debug mode. 

Note that you can also define custom NetBeans actions to use the Run and Debug buttons. Add a `nbactions.xml` file to the root of your project, with:

```
<actions>
	    <action>
	        <actionName>run</actionName>
	        <goals>
	            <goal>clean</goal>
	            <goal>javafx:run</goal>
	        </goals>
	    </action>
	    <action>
	        <actionName>jlink</actionName>
	        <goals>
	            <goal>clean</goal>
	            <goal>javafx:jlink</goal>
	        </goals>
	    </action>
	    <action>
	        <actionName>debug</actionName>
	        <goals>
	            <goal>clean</goal>
	            <goal>javafx:run@debug</goal>
	        </goals>
	    </action>
	</actions>
```

Then you will need to go to NetBeans, and test the run button. 

To debug, add first some breakpoints, press the debug button, and go to NetBeans -> Debug -> Attach debugger, and add a debugger in localhost, port 8000. Once you press ok, the debugger will start (might take a few seconds).

**Comment by swinkel-git** [comment]
Thank you for the detailed and good answer. I'm glad, it works :-)

**Comment by rrohm** [comment]
Hello, 
the solution works, but is there any way to make it work out-of-the-box, and without the two-step-solution of having to issue "debug" and then "attach debugger"?
Compared to debugging other Mavein+Java projects or JavaFX with Ant (NB8/JDK8), this does not feel good ...
Should I creat a new ticket for this, or did I miss something?

Best regards, 
Robert

**Comment by wiegleyj** [comment]
I'd second this. Why do traditional projects run and debug with a single button click in Netbeans but a modern modular javafx needs all this cryptic work?

I also think a ticket should be created to help drag this into the year 2020.
