### ISSUE TITLE
can not start javafx project

### ISSUE THREAD

**Issue by abdullanablsi** [openjfx/openjfx-docs#114]
Error: Could not find or load main class application.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by sharidass1408** [comment]
I am facing the same issue in my project.

**Comment by ToORAGe** [comment]
Have the same issue, using Adopt OpenJDK and OpenJFX.

**Comment by jperedadnr** [comment]
@sharidass1408 your `jar` task should use `configurations.runtimeClasspath`, as now the JavaFX plugin uses `implementation` instead of the deprecated `compile` (that is why `configurations.compile` doesn't include the JavaFX classes in the fat jar).

The docs/sample already contain this change. See for instance this [build](https://github.com/openjfx/samples/blob/master/CommandLine/Non-modular/Gradle/hellofx/build.gradle#L29).
