### ISSUE TITLE
Windows Getting Started Fault

### ISSUE THREAD

**Issue by u6630774** [openjfx/openjfx-docs#85]
On Windows, the following command is deceptive: `javac --module-path %PATH_TO_FX% --add-modules=javafx.controls,javafx.fxml HelloFX.java` because it will report the error: invalid flag

Reason: Doesn't interpret Program Files as program files but instead "Files".

Correctable to:  `javac --module-path "%PATH_TO_FX%" --add-modules=javafx.controls,javafx.fxml HelloFX.java`

**Comment by htwberlinimi** [comment]
Another way to work around this is to set the complete PATH_TO_FX environment variable into double quotes, like:

PATH_TO_FX="C:\Program Files\JavaFX\javafx-sdk-11.0.2\lib"
 or
PATH_TO_FX = "%ProgramFiles%\JavaFX\javafx-sdk-11.0.2\lib"

Alternatively just add double quotes to the part of the path containing white space:

PATH_TO_FX="C:\Program Files"\JavaFX\javafx-sdk-11.0.2\lib
or
PATH_TO_FX="%ProgramFiles%"\JavaFX\javafx-sdk-11.0.2\lib

All these solutions are a bit easier, since you don't need to add the double quotes on each javac call on the command line...

**Comment by abhinayagarwal** [comment]
I do not see this as a fault in the documentation.

It depends on the JDK path. If the path contains space, it is the responsibility of the user to make necessary changes either to the environment variable or to the java/c command.
